routes/web.php
h<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('/test', function(){
   return view('testBarrocPage');
});

Route::resource('workOrder', 'workOrderController');
Route::resource('purchases', 'PurchaseController');
Route::resource('supplies', 'SuppliesController');
Route::resource('ContactForm', 'ContactFormController');
Route::resource('error', 'ErrorController');
Route::resource('quotations', 'QuotationsController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'usersController');
// Route::get('user.master', 'usersController');

Route::post('/supplies/filter', 'SuppliesController@filter')->name('supplies.filter');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @auth
                        @foreach($users as $user)
                        <h3><strong>welkom, {{ $user->name }}</strong></h3>
                            @endforeach
                        <h5>your info</h5>
                        <ul>
                            @foreach ($users as $user)
                                <li>name: {{$user->name}}</li>
                                <li>email: {{$user->email}}</li>
                                @if($user->role_id == 1)
                                    <a href="{{ route('users.index', $user->role_id) }}">bewerk persoongegevens</a>

                                @endif
                                @if($user->role_id == 4)
                                    <li>positie: maintenance medewerker</li>
                                    <a href="{{ route('error.index') }}">error lijst</a>
                                @endif
                                @if($user->role_id == 7)
                                    @foreach($contractsInfo as $contractInfo)
                                    <div class="contract-info border border-info">
                                        <div class="invoices border-right">
                                            <h4>Contract Info
                                            </h4>
                                            <p>invoices nr: {{ $contractInfo->invoicesnummer }}</p>
                                            <p>contract nr: {{ $contractInfo->quotationsnummer }}</p>
                                            <p>lease nr: {{ $contractInfo->leasenummer }}</p>
                                            <p>naam: {{ $contractInfo->name }}</p>
                                            <p>prijs: {{ $contractInfo->price }}</p>
                                            @if(empty($contractInfo->betaald_op))
                                                <p>nog niet betaald</p>
                                                @else
                                            <p>betaald op: {{ $contractInfo->betaald_op }}</p>
                                                @endif
                                            <p>financiën goedkeuring: @if($contractInfo->finance_approved == 0) niet goed gekeurd @elseif($contractInfo->finance_approved == 1)
                                            goed gekeurd @endif</p>
                                            <p>klant goedkeuring: @if($contractInfo->customer_approved == 0) niet goed gekeurd @elseif($contractInfo->customer_approved == 1)
                                                    goed gekeurd @endif</p>
                                        </div>
                                    </div>
                                    @endforeach
                                    <a class="btn btn-info" href="{{ route('error.create') }}">maak storing melding</a>
                                    <a href="{{ route('users.edit', $user->role_id) }}">bewerk gegevens</a>
                                @endif
                                @if($user->role_id == 3)
                                    <li>positie: medewerker finance</li>
                                @endif
                                @if($user->role_id == 6)
                                    <li>positie: medewerker inkoop</li>
                                @endif
                                @if($user->role_id == 2)
                                    <li>positie: medewerker sales</li>
                                    <a href="{{ route('users.create', Auth::id())}}">klant aanmaken</a>

                                @endif
                            @endforeach
                        </ul>
                    @endauth
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/quotation.blade.php
@extends('layouts.app')
@section('content')
    <div class="parallax">
        <div class="central">
            <div class="content">
                <div class="form-group form">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </div>
                    @endif
                    <form action="{{ route('quotations.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
                        </div>

                        <div class="form-group">
                            <label for="price">price</label>
                            <input class="form-control" type="number" name="price" id="price"  value="{{ old('price') }}">
                        </div>

                        <div class="form-group">
                            <label for="price_vat">price with vat</label>
                            <input class="form-control" type="number" name="price_vat" id="price_vat" value="{{ old('price_vat') }}">
                        </div>

                        <div class="form-group">
                            <label for="bkr_check">BKR check</label>
                            <input name="bkr_check" id="bkr_check" type="checkbox" required>
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="make quotations">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection