routes/web.php
h<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('/test', function(){
   return view('testBarrocPage');
});

Route::resource('workOrder', 'workOrderController');
Route::resource('purchases', 'PurchaseController');
Route::resource('supplies', 'SuppliesController');
Route::resource('ContactForm', 'ContactFormController');
Route::resource('error', 'ErrorController');
Route::resource('quotations', 'QuotationsController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'usersController');
// Route::get('user.master', 'usersController');

Route::post('/supplies/filter', 'SuppliesController@filter')->name('supplies.filter');

resources/views/purchases/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container-fluid">
        <form action="{{route('purchases.store' )}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-3">Naam product</div>
                <div class="col-md-3">Prijs</div>
                <div class="col-md-3">Voorraad</div>
                <div class="col-md-3">bestellen</div>
                @foreach($supplies as $supply)
                    <div class="col-md-3">{{$supply->name}}</div>
                    <div class="col-md-3">{{$supply->price}}</div>
                    <div class="col-md-3">{{$supply->amount}}</div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <input type="hidden" name="">
                            <input type="number" name="{{$supply->id}}" id="{{$supply->id}}">
                        </div>
                    </div>
                @endforeach

                <input type="submit" class="btn btn-success">
            </div>
        </form>
    </div>
@endsection

resources/views/purchases/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="parallax">
        <div class="container">
    @foreach($purchases as $purchase)
        <div class="user_name">Naam van inkoopmedewerker: {{ $purchase->user->name }}</div>
        <a href="{{ route('purchases.show', $purchase) }}">Bekijik hem hier</a>
    @endforeach
        </div>
    </div>
@endsection

resources/views/purchases/show.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <div class="headflex">
                <div style="margin-top: 50px;">
                    <div class="logo">
                        <div class="left_corner_logo logo_text"><p>BARROC</p></div>
                        <div class="logo_image"></div>
                        <div class="right_bottom_logo logo_text"><p>INTENSE</p></div>
                    </div>
                </div>
                <div class="listflex">
                    <h1>besteloverzicht</h1>
                    <h4>bestelnummer {{$purchase->id}}</h4>
                    <div class="productsButton">
                        <ul>
                            @foreach($purchase->supplies as $supply)
                                <li>{{$supply->name}}</li>
                                <li>{{$supply->price_per_unit}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
@endsection