routes/web.php
h<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('/test', function(){
   return view('testBarrocPage');
});

Route::resource('workOrder', 'workOrderController');
Route::resource('purchases', 'PurchaseController');
Route::resource('supplies', 'SuppliesController');
Route::resource('ContactForm', 'ContactFormController');
Route::resource('error', 'ErrorController');
Route::resource('quotations', 'QuotationsController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'usersController');
// Route::get('user.master', 'usersController');

Route::post('/supplies/filter', 'SuppliesController@filter')->name('supplies.filter');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/usersController.php
<?php

namespace App\Http\Controllers;

use App;
use \App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PharIo\Manifest\Email;

class usersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        $errors = \DB::select("SELECT * FROM errors");
        $contractsInfo = \DB::select("SELECT invoices.id AS invoicesnummer,
     quotations.id AS quotationsnummer,
     invoices.lease_id AS leasenummer,
      invoices.betaald_op,
       quotations.name,
        quotations.price,
         quotations.price_vat,
          quotations.finance_approved,
           quotations.customer_approved 
           FROM invoices 
           INNER JOIN leases ON invoices.lease_id = leases.id 
           INNER JOIN users ON leases.customer_id = users.id 
           INNER JOIN quotations ON users.id = quotations.customer_id 
       WHERE quotations.customer_id = $id");
        $users = User::where('role_id', 7)->get();
        if($id != 1){return view('home', ['users' => $users, 'contractsInfo' => $contractsInfo, 'errors' => $errors]);}
        else {
            return view('users.index', ['users' => $users]);
        }

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create ()
    {
        $id = Auth::id();
        $users = \DB::select("select * from users");
        return view('users.create', ['users' => $users]);



    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        user::insert([
            'name' => $request->name,
            'email' => $request->email,
            'role_id' => $request->role,
            'password' => $request->Password
        ]);

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editingthe specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::id();
        $customer = User::find($user);
        return view('users.edit', ['customer' => $customer]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->update([
            'name' => $request->name,
            'email' => $request->email
        ]);

        return redirect()->route('users.index', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
    @extends('layouts.app')

@section('content')

    <form action="{{ route('users.store') }}" method="post">
        @csrf

        <div class="form-group">
            <label for="Name">Name</label>
            <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
        </div>

        <div class="form-group">
            <label for="Email">Email</label>
            <input class="form-control" type="email" name="email" id="email" value="{{ old('email') }}">
        </div>

        <div class="form-group">
            <label for="Role">Role</label>
            <input class="form-control" type="" name="role" id="role">
        </div>

        <div class="form-group">
            <label for="Password">Password</label>
            <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
        </div>


        <div class="form-group">
            <input type="submit" value="Create User">
        </div>
    </form>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>bewerk gegevens</h1>
    <form action="{{ route('users.update', $customer->id, $request->id) }}" method="POST">
        @method('PUT')
        @csrf
        @if(Auth::id() != 1)
        <div class="form-group">
            <label for="">name</label>
            <input name="name" type="text" value="{{$customer->name}}">
            <input name="email" type="text" value="{{$customer->email}}">
        </div>
        @else
            <div class="form-group">
                <label for="">name</label>
                <input name="name" type="text" value="{{ $request->name}}">
                <input name="email" type="text" value="{{ $request->email}}">
            </div>
        @endif
        <input type="submit" value="bewerk gegevens">
    </form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
    <ul>
        @foreach($users as $user)
        <li><a href="{{ route('users.edit', $user->id) }}">{{ $user->name }}</a></li>
        @endforeach
    </ul>
    @endsection