routes/web.php
h<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('/test', function(){
   return view('testBarrocPage');
});

Route::resource('workOrder', 'workOrderController');
Route::resource('purchases', 'PurchaseController');
Route::resource('supplies', 'SuppliesController');
Route::resource('ContactForm', 'ContactFormController');
Route::resource('error', 'ErrorController');
Route::resource('quotations', 'QuotationsController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'usersController');
// Route::get('user.master', 'usersController');

Route::post('/supplies/filter', 'SuppliesController@filter')->name('supplies.filter');

app/Supply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supply extends Model
{
    //
}

app/Http/Controllers/SuppliesController.php
<?php

namespace App\Http\Controllers;

use App\PurchaseRule;
use App\Purchase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Supply;
use PharIo\Manifest\Requirement;


class SuppliesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function filter(Request $request)
    {
        $btn = $_POST['submitbtn'];
        if ($btn == "clear"){
            $supplies = Supply::all();
            return view('supplies/index', ['supplies' => $supplies]);
        }

        $name = $request->input('Name');
        $supplies = Supply::where('name')
            ->orWhere('name', 'like', '%' . $name . '%')->get();

        $checkbox_stock = $request->input('enough', false);
        if ($checkbox_stock == 'to-little')
        {
            $supplies = Supply::where('amount')
                ->orwhere('amount', '<', 3)->get();
        }
        if ($checkbox_stock == 'enough')
        {
            $supplies = Supply::where('amount')
                ->orwhere('amount', '>', 3)->get();
        }

        return view('supplies/index', ['supplies' => $supplies]);
    }
    public function index()
    {
        $supplies = Supply::all();
        return view('supplies/index',['supplies'=>$supplies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $purhaseId = Purchase::insertGetId([
            'user_id' => Auth::id(),
            'created_at' => now(),
            'updated_at' => now()
        ]);

        PurchaseRule::insert([
            'purchase_id' => $purhaseId,
            'amount' => $request->amount,
            'supply_id' => $request->supplyid,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        return redirect()->route('supplies.show', $request->supplyid);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(\App\Supply $supply)
    {
        return view('supplies/show', ['supply' => $supply] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/supplies/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
    <form action="{{route('supplies.filter')}}" method="post">
        @csrf
        <div class="form-group">
            <input type="text" name="Name">
            <input type="submit" name="submitbtn" value="Search">
            <input type="submit" name="submitbtn" value="Clear">
        </div>
        <div class="form-group">
            <input type="radio" value="enough" name="enough"> Momenteel leverbaar
            <input type="radio" value="to-little" name="enough"> Niet meer op voorraad
        </div>
    </form>

    <div class="container-fluid">
        <div class="row">


            <div class="col-4">Naam product</div>
            <div class="col-4">Prijs</div>
            <div class="col-4">Voorraad</div>
            @foreach($supplies as $supply)
                <div class="col-4"> <a href="{{ route('supplies.show', $supply->id ) }}"> {{ $supply->name }}  </a>   </div>
                <div class="col-4">{{$supply->price}}</div>
                <div class="col-4">{{$supply->amount}}</div>
            @endforeach
        </div>

    </div>
    </div>





@endsection

resources/views/supplies/show.blade.php
@extends('layouts.app')
@section('content')

<form action="{{ route('supplies.store') }}" method="post">
    @csrf

    <h1 class="card-title"> {{ $supply->name }} </h1>

    <p class="card-text"> {{ $supply->price }} </p>
    <input type="number" name="supplyid" value="{{$supply->id}}" class="hidden">

    <div class="form-group">
        <label for="amount">amount</label>
        <textarea name="amount"></textarea>
    </div>

    <div class="form-group">
        <input type="submit" value="Order this product">
    </div>
</form>

@endsection